import Link from "next/link";
import { DESTINATIONS } from "@/lib/catalog/destinations";
import { Logo } from "./logo";

const POPULAR = ["bangkok", "istanbul", "london", "tbilisi", "bali", "maldives"];

export function Footer() {
  const popular = DESTINATIONS.filter((d) => POPULAR.includes(d.slug));
  return (
    <footer className="mt-24 border-t bg-card pb-24 md:pb-0">
      <div className="container-page grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-4">
        <div className="space-y-3">
          <Logo />
          <p className="max-w-xs text-sm text-muted-foreground">
            Deal discovery for curious travellers. We surface unusually cheap fares so you can decide where to go next.
          </p>
        </div>
        <FooterColumn
          title="Discover"
          links={[
            { href: "/explore", label: "Explore anywhere" },
            { href: "/deals", label: "Today's deals" },
            { href: "/deals?collection=weekend", label: "Weekend escapes" },
            { href: "/destinations", label: "All destinations" },
          ]}
        />
        <FooterColumn
          title="Popular"
          links={popular.map((d) => ({ href: `/destinations/${d.slug}`, label: `Flights to ${d.city}` }))}
        />
        <FooterColumn
          title="Your account"
          links={[
            { href: "/alerts", label: "Price alerts" },
            { href: "/favorites", label: "Saved flights" },
            { href: "/dashboard", label: "Dashboard" },
            { href: "/signup", label: "Create an account" },
          ]}
        />
      </div>
      <div className="border-t">
        <div className="container-page flex flex-col gap-2 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
          <p>© {new Date().getFullYear()} SkyScout. Fares are indicative and change frequently.</p>
          <p>Demo data: prices are generated by SkyScout&apos;s sample provider, not live airline inventory.</p>
        </div>
      </div>
    </footer>
  );
}

function FooterColumn({ title, links }: { title: string; links: { href: string; label: string }[] }) {
  return (
    <div>
      <h2 className="text-sm font-semibold">{title}</h2>
      <ul className="mt-3 space-y-2">
        {links.map((l) => (
          <li key={l.href}>
            <Link href={l.href} className="text-sm text-muted-foreground transition-colors hover:text-foreground">
              {l.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
